### ISSUE TITLE
module.exports.EXPRESSIONS

### ISSUE THREAD

**Issue by stovesy** [eerotal/LibreSignage#104]
Could you externalise this from the main.js file to allow additional customization ?
Or parse it from a simple json file or files. This way users could build up a custom set of markup attributes - I'd like to customize the background colour etc, have divs with a background.

Maybe optional parameters for a markup tag ?

**Comment by eerotal** [comment]
A system for implementing new markup tags as plugins is planned and will be implemented at some point. I don't think parsing the main definitions from an external source is a very good idea, since it would basically make every LibreSignage parse it's own version of the markup. Btw, support for changing background colors of divs is coming in v1.1.0 which is due to be released soon.
