### ISSUE TITLE
Programatically generate slides and import them?

### ISSUE THREAD

**Issue by beville** [eerotal/LibreSignage#108]
Just discovered LibreSignage, looks very cool and I'm trying to work out if I can use it how I want.

I'd like to programmatically generate slides (and update a queue) from RSS and other online content and then automatically import them into LibreSignage, and have the modified queue be displayed to the clients without any manual refresh.

I have a docker instance running on my machine right now, and I see that the test slides and queues that I created with the UI exist under "/var/lib/docker/volumes/ls_vol/_data". I'm guessing that if I were to create the correct json files, I could just copy them under the "slides" folder, but would modifying a "live" queue file be problematic?

Or maybe there is a better (and recommended) method for what I'm thinking of?

**Comment by eerotal** [comment]
You could technically create the slide files manually but I don't recommend that since the file formats can change and it's not a very robust solution. However, LibreSignage has an API that you could use instead.

Documentation for the API is automatically generated by Doxygen if you build LibreSignage from source and run `make doxygen-docs`. You can access the documentation by opening `doxygen_docs/html/index.html` in your browser. The API endpoints are documented under `Files -> src -> public -> api -> endpoint`. I can give you some pointers on how to use the API if you end up trying it out.

**Comment by beville** [comment]
Thanks. I was able to work out enough from the code to figure out the API.  It was pretty straightforward.

Here's a version of the python script I put together, if anyone needs a reference:  https://gist.github.com/beville/6b0f03fc3093eb47840401ba4e8123ac
