### ISSUE TITLE
Cannot upload media

### ISSUE THREAD

**Issue by MatthK** [eerotal/LibreSignage#137]
Either I am too stupid or this software is extremely buggy.

After I have completely started from scratch, got the container running, tested a first queue, created a few slides. Uploaded media, all went fine.

I then added two changes to the config files by adding new php files 02-name.php to increase the quota and email address of the admin. They show in the control panel as expected.

Then I wanted to add more slides on the queue created earlier, but now I can't upload any media. The console just comes up with the following error message:

`Uncaught (in promise) TypeError: e.get_code is not a function
    handle_error https://libresign.nhz.ch/control/editor/js/main.js:226635
    upload_assets https://libresign.nhz.ch/control/editor/js/main.js:224456`

How do I get this to work again?

**Comment by MatthK** [comment]
It seems it's the same error that I have encountered previously. In a different browser it says "Entity Too Large". The file is 2.90MB. But I did upload the very same file previously to another instance.

```
POST https://domain.name/api/endpoint/slide/asset/slide_upload_asset.php 413 (Request Entity Too Large)
(anonymous) @ VM1500:1
(anonymous) @ main.js:226890
call @ main.js:226832
upload_assets @ main.js:230188
upload_assets @ main.js:224613
upload_assets @ main.js:224450
click @ main.js:224293
(anonymous) @ main.js:230564
dispatch @ main.js:66041
elemData.handle @ main.js:65848
```

A smaller file of only 369KB can be uploaded. Is there a limit to define in one of the config files?

**Comment by eerotal** [comment]
It seems like there's a bug in the error handling code which is why you're seeing the `e.get_code is not a function` error in so many places and even when the "error" response isn't actually a real error to the user. I need to look into that. It's quite odd that you're getting the `Entity Too Large` response, even though the LibreSignage Docker images are configured to accept files as large as 200M by default. Are there any differences between the instance where the file upload works and the one where it doesn't?

**Comment by MatthK** [comment]
No, there should be no difference. The only difference it seems is that I have deleted the standard users and created new ones, and added the config files to increase the quota/email address of the admin.

**Comment by eerotal** [comment]
I just read through some code and immediately noticed what's causing the `e.get_code is not a function` errors. I must have changed some function names during refactoring at some point and forgot to change them in the error handling code. Normal errors should only cause a popup to be displayed but because of the bug the popup code doesn't work and throws that error you're seeing. This is already fixed in the next branch as a byproduct of larger rewrite though. I really need to get the next version released soon because it contains a lot of important bug fixes.

I probably figured out the `Request Entity Too Large` issue aswell. You seem to be running LibreSignage over TLS. If you're running LibreSignage behind a reverse proxy, you probably need to do some additional configuration. Did you by any chance use nginx and [this](https://github.com/eerotal/LibreSignage/blob/master/src/doc/rst/reverse_proxy.rst) configuration?

**Comment by MatthK** [comment]
Yes, I have it behind a reverse proxy and had that configuration.

I have added the 'client_max_body_size 200M;' to it and I can now upload the files. Excellent!

**Comment by eerotal** [comment]
Great! I'll add the line to the documentation aswell.

**Comment by MatthK** [comment]
Thanks for the quick reply. Awesome!!
