### ISSUE TITLE
Exporting Queues

### ISSUE THREAD

**Issue by jjasghar** [eerotal/LibreSignage#152]
Is there a way to export a queue to another instance of LibreSignage? I'm thinking of leveraging this for a project, but I need to collaborate with a couple of other people.

I'd love to be able to export out my queue/slides (maybe upload to a `git` repo) and then import it into another instance.

**Comment by eerotal** [comment]
This should be possible by just copying the queue .json file from `/var/www/<hostname>/queues/` and all the required slide data directories from `/var/www/<hostname>/slides/` over to the new system. The new system must also have the same users configured for permissions to work. There might also be something else I'm overlooking here because I have never done this myself.

**Comment by jjasghar** [comment]
ah! nice. thanks. unfortunately, I use the docker deployment, so that means I'd have to break in and copy them out right?

**Comment by mauro2306** [comment]
If you used the volume feature, you should be able to access it from the host without that much of a pain, that's how i do it to not loose anything
