### ISSUE TITLE
Installation on Ubuntu or Debian

### ISSUE THREAD

**Issue by felix-wo** [eerotal/LibreSignage#26]
Dear eerotal,

the Projekt looks promising to me. Thank you for sharing your work!

I’m trying to get it running, but still struggling on either Ubuntu 18.04 or Debian 9.6. In both cases I get to the Site over the browser, but no CSS seems to be rendered. On Ubuntu in drops error messages in the browser as well. In both cases I remember error messages during installation but didn’t save them, as I’ve just made quick attempts to install so far.

Of course, I’m willing to try again and to provide any detailed information. But wouldn’t it make sense, you would provide a step-by-step installation guide for a specific OS, such as Ubuntu 18.04 or Debian 9(.6)? 

Your installation guide here on the main page seems not to be complete. On Debian 9.6 `build-essential` was missing, and It doesn’d provide php 7.0 from the packages, but 7.0. Having a standardized installation and knowing exactly what packages are to be installed (OS, php, nodejs …) would help testing and troubleshooting.

Thanks a lot!

**Comment by eerotal** [comment]
Thanks for your feedback! The installation instructions in the readme are for Debian but since Ubuntu is based on Debian the instructions should work there too. Anyway, I spun up a fresh VM with Debian stable and tried the install process and indeed, it didn't work. There were a few errors in the readme and problems with the SCSS to CSS compilation and PHP syntax support.

As you said, `build-essential` was missing from the readme. Actually the whole build-essential metapackage is not needed as only GNU make is used by the build system. I updated the readme to include that.

The problem with SCSS to CSS compilation was due to the Debian repos having a very old version of the SCSS compiler ruby-sass, which in turn caused problems while compiling the Bootstrap sources. I solved that by using the JavaScript based compiler from npm instead. I would guess this problem is why CSS didn't load on your installation.

Now the case with PHP on Debian stable is quite interesting. PHP 7.2 is only in the testing and unstable repos, and stable only has the 7.0 release. 7.0 is, however, marked End Of Life on 3rd December 2018, so it has one day of security support left. I don't know what plan the Debian maintainers have, maybe they will even continue supporting PHP 7.0 until Debian Stretch is not supported anymore. Anyway, I made some changes to the LibreSignage PHP code to make it work with PHP 7.0 too.

I pushed the changes to the 0.2.2-dev branch, so it'd be great if you could give them a try and report back here. That branch also has some other fixes for the 0.2.2 release which is due to be released in a couple of days.

**Comment by felix-wo** [comment]
Thank you for your quick reply and your efforts! Got it working that way on Debian Stretch! Yes, I had error messages concerning SASS.

What I see looks really useful so far to me. Will report further questions separately …

By the way, either Debian and Ubuntu maintain php with security patches until the EoL of their respective OS versions, as PHP is in stable or, respectively, main repository.

**Comment by eerotal** [comment]
Great! I'll close this issue.
