### ISSUE TITLE
Media cannot be added to slide

### ISSUE THREAD

**Issue by herrzhull** [eerotal/LibreSignage#31]
Hello,

First off: the idea of this is great, thanks for your time and effort :).
But I did notice a couple of issues:
- The upload button does not work in chrome. In firefox it does seem to do what it's supposed to.
- Am I correct I can only add a single image in the media gallery per slide? And if so: why would that be? I'm sitting on a rather large VM so I don't really need any limitations.
- The tag for media doesn't seem to work on my end: 
`[img url=<URL> width=<width> height=<height>][/img] `
throws 
`Unexpected token: '/'. Expected ']' (@ 1:15)`
I get this when I do, for example:
`[img url=https://xxx.com/xxx.jpg width=50% height=50%][/img]`
- having the option to add html to certain slides would make this awesome (or just a button to switch between code and markup).

Thanks for any feedback which could help me to get this to work!

**Comment by eerotal** [comment]
- First of all, please make sure you're using the latest version of LibreSignage. There were some problems with uploading media in older versions. The newest stable release is v0.2.2. At least on my system and with v0.2.2 the upload button works in both Chrome and Firefox.
- The number of files you can upload per slide can be configured in the configuration files. The default is 2 files per slide, which I should actually increase since it's quite restrictive. Did you have problems with uploading multiple files? Again, any problems *might* be due to using an older version so please check that first.
- You need to use quotes in the URL. Your example would then become `[img url="https://xxx.com/xxx.jpg" width=50% height=50%][/img]`
- I have considered implementing a way to use HTML for slides and I'll keep your suggestion in mind.

Thanks!

**Comment by herrzhull** [comment]
Thanks for the swift reply! It does indeed work now :). And with the latest chrome the issue with the button also seems resolved! The obligatory image % does require some guessing in order to make images not show up stretched out of proportion, but I'm still finding my way around. I'm looking forward to the HTML implementation! Cheers!
