### ISSUE TITLE
Slides are limited to 40 seconds?

### ISSUE THREAD

**Issue by infomaniac50** [eerotal/LibreSignage#51]
My use case is to run sponsored videos during sporting events. Some of the videos are longer than 40 seconds but the slides are limited to 40 or less.

Is there a technical reason why slides are limited to 40 seconds? I remember something about accuracy issues with the slide timer. So maybe it was to prevent the slides from getting too far out of sync with the timer.

If it won't cause a problem, I would leave the upper limit uncapped. The lower limit makes sense because you don't want the browser trying to fetch as fast as possible. The upper limit is strange though since you can put just about anything in the markup editor. You could put a 1h:30m movie in there and it would only play for the first 40 seconds.

**Comment by eerotal** [comment]
The slide duration is limited to 40 seconds by default just to make sure users can't create slides that take a massive amount of time accidentally. That would also be annoying for other users of the same queue because they can't fix the slide timing and the queue would be effectively useless.

That said, the maximum duration is configurable in the config files. The default duration is set in `config/limits/00-default.php`. The name of the parameter is `SLIDE_MAX_DURATION`. The *Docker* help document has some instructions on using the config files. The *Configuration* help page seems to be outdated so don't use that.

**Comment by infomaniac50** [comment]
I was able to fix this issue using the config.
