### ISSUE TITLE
Some basic API examples for Curl or Postman

### ISSUE THREAD

**Issue by dekke046** [eerotal/LibreSignage#82]
Hi,

Trying to use the API to update a slide is bringing some issues.
The API docs are not that clear and missing a few basic examples.

For example I guess I need to sign in first (get a cookie) with a HTTP POST:
`curl -X POST -Hame":"display", "password":"display", "who":"displayuser", "permanent":"TRUE"}' http://localhost/api/endpoint/auth/auth_login.php`

This nicely gives a, what I suppose, succesful login:
```json{
  "user": {
    "user": "display",
    "groups": [
      "display"
    ],
    "sessions": [
      {
        "id": "display_1563821460",
        "who": "displayuser",
        "from": "172.17.0.1",
        "created": 1563821460,
        "max_age": 600,
        "permanent": true
      },
      {
        "id": "display_1563821488",
        "who": "displayuser",
        "from": "172.17.0.1",
        "created": 1563821488,
        "max_age": 600,
        "permanent": true
      }
    ],
    "quota": {
      "limits": {
        "slides": {
          "limit": 10,
          "description": "Slides"
        },
        "api_rate": {
          "limit": 200,
          "description": "API quota (calls/60s)"
        }
      },
      "used": {
        "slides": 0,
        "api_rate": 2
      }
    }
  },
  "session": {
    "id": "display_1563821488",
    "who": "displayuser",
    "from": "172.17.0.1",
    "created": 1563821488,
    "max_age": 600,
    "permanent": true,
    "token": "9f359b791dda36ecd9e7e0c7200d0e"
  },
  "error": 0
}
````

But how to move from here?
I have been trying to do a get 

> http://localhost/api/endpoint/slide/slide_list.php

To find the correct slide ID and then do a slide_get.php and a slide_save.php.

Could someone point me a bit more in the right direction?

Thanks,

Maarten

**Comment by eerotal** [comment]
Okay, so you have the login part figured out already. That's a successful login.

To use endpoints that require authentication, you need to pass the session token from `response.session.token` in the Auth-Token header. Here `response` is the response JSON object you got from `auth_login.php`.

In general, when a call to an endpoint is successful, the`error` field in the response is 0 and some data might be returned. Not all endpoints return data though. In the current version of LibreSignage, the `error` value is guaranteed to exist. In upcoming versions there's some changes to how API errors are indicated but this is all you need to know for now.

When trying out the API, I recommend you to build LibreSignage with debugging enabled. Debugging enables verbose error messages through the API to give a hint about what might have gone wrong. There can sometimes be errors due to things you might not expect like values being out of the accepted range etc.

You can call `slides_list.php` to get an array of all slide IDs in all queues. You just need to do a GET to `api/endpoint/slide/slides_list.php`.

You can then POST to `slide_get.php`. You must pass the ID of the slide you want to fetch in the request body as JSON like so: `{"id": "ID HERE"}`. This should then return the slide data for the requested slide.

`slide_save.php` is a bit more complicated. First of all, you can only call it if you're logged in with a user who's in the editor or admin groups. Also, if you want to modify an existing slide, you either need to be the owner of that slide or a collaborator. This means that you can't edit slides with the `display` user.

So, once you're logged in with a proper user, you can call the `slide_save.php` endpoint. You can pass all the slide data parameters you got from `slide_get.php` back into this one, although some of them are not actually used. Check out the documentation for `slide_get.php` in the web interface docs. There's some more info on what parameters you can/must pass to the endpoint. If everything goes as expected, the data is saved on the server and an error code set to 0 is returned along with all the saved data.

**Comment by dekke046** [comment]
Excellent!

This clears my questions, thanks!

Maarten
