### ISSUE TITLE
I am trying to uploading a 15kb js file through github UI, its show error " upload file less than 25mb "

### ISSUE THREAD

**Issue by kirti114** [eerotal/LibreSignage#84]
I am trying to uploading a 15kb js file through github UI, its show error " upload file less than 25mb "
its a simple nodejs file.
please solve it.

**Comment by eerotal** [comment]
I don't really understand what you're trying to say. You tried to upload a JS file to LibreSignage? Through GitHub's UI? Also, I don't think LibreSignage

First of all, you can't upload JS files to a LibreSignage server because it's not an allowed filetype. And what does GitHub's UI have to do with that?
