### ISSUE TITLE
Redirects to local hostname behind reverse proxy

### ISSUE THREAD

**Issue by tostiheld** [eerotal/LibreSignage#85]
I'm trying to use LibreSignage behind a reverse proxy, but it refuses to use the public hostname. I have tried to override the Host header in my reverse proxy configuration, but the application keeps redirecting to its local hostname. Is there any configuration option I am missing or is it simply not possible to use LibreSignage behind a reverse proxy?

**Comment by eerotal** [comment]
Interesting. I haven't tried to host LibreSignage behind a reverse proxy so I'm not yet sure what's going wrong. It seems like the server might be sending redirects that aren't compatible with a reverse proxy.

I need to setup a reverse proxy and try this one out myself.

**Comment by eerotal** [comment]
Okay, I tried setting up an Apache2 reverse proxy with the following configuration in `/etc/apache2/sites-available`.

```
Listen 8080

<VirtualHost *:8080>
	ServerName example.com
	ProxyPass / http://127.0.0.1:9090/
	ProxyPassReverse / http://127.0.0.1:9090/
</VirtualHost>

```

I also edited my LibreSignage VirtualHost config so that it listens on port 8080 instead of 80 so that any direct redirects to the backend server will break.

Then I enabled `mod_proxy` and `mod_http_proxy`.

I also added `127.0.0.1 example.com` to my `/etc/hosts`.

Now when I connect to `example.com:8080` the reverse proxy forwards my request to the LibreSignage backend (127.0.0.1:9090) without any problems. Redirects etc. all work fine. I even checked the requests my browser is making and they all seem to go to `127.0.0.1:9090`, which is the reverse proxy.

Now I'm very much a rookie when it comes to reverse proxies so there may well be something I'm missing here. Btw, did you use apache2 or nginx for you reverse proxy? That might also have something to do with the problem.

**Comment by tostiheld** [comment]
Okay, I was using nginx with the following configuration:

```
location / {
        set $upstream http://libresignage;
	proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host my.domain.name;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_pass $upstream;
}
```

Where http://libresignage is the hostname of my container. This config works for most web applications on my end, I'm not completely sure what causes the faulty redirects for this one.

**Comment by eerotal** [comment]
I tried setting up an nginx reverse proxy with the same config you used, but I can't seem to reproduce this issue.

* What version of LibreSignage are you using?
* Are you running a Docker image or a native install?
* What redirects exactly do not work?

**Comment by tostiheld** [comment]
I haven't had time to look into it until now, so here we go again.

- I am using version 1.0.1
- I am using a docker image
- After installation, it redirects to <internal_hostname>/control

I am going to mess with my nginx config some more, if you think that that is where the issue lies.

**Comment by tostiheld** [comment]
Okay, I really don't understand, but for some reason everything is working perfectly now. Thanks for your time anyways.
